from snakemake.shell import shell


shell.executable("bash")

import pandas as pd

samples = "1 2 3".split()
cells = "fibroblast keratinocyte melanocyte".split()


prefix = config["prefix"]

sample_sheet = pd.read_table(config["sample_sheet"], sep=" ")
ss = sample_sheet


rule all:
    input:
        expand("{prefix}/data/epic-merge/{caller}/matrixes.gz",
               prefix = prefix,
               cell=cells,
               caller="epic".split()), # macs2
        f"{prefix}/data/epic-merge/test/matrixes.gz"



def get_files(w, chip):

    celltype = w.cell

    files = list(ss.loc[(ss.ChIP == chip) & (ss.Group == celltype)].Path)

    return files


rule run_epic:
    input:
        chip = lambda w: get_files(w, "ChIP"),
        input = lambda w: get_files(w, "Input"),
    output:
        csv = "{prefix}/data/epic/{cell}.csv",
        bed = "{prefix}/data/epic/{cell}.bed",
        matrix = "{prefix}/data/epic/{cell}.matrix.gz",
    threads:
        48
    shell:
        "epic -cpu {threads} -g 3 -w "
        "200 -gn hg19 " # -fs 200 "
        "-b {output.bed} -t {input.chip} -c {input.input} "
        "-sm {output.matrix} "
        "> {output.csv}"


rule run_macs2:
    input:
        chip = lambda w: get_files(w, "ChIP"),
        input = lambda w: get_files(w, "Input"),
    output:
        bed = "{prefix}/data/macs2/{cell}.bed",
    params:
        prefix = "{prefix}/data/macs2/{cell}",
        outfile = "{prefix}/data/macs2/{cell}_peaks.broadPeak"
    conda:
        "envs/macs2.yaml"
    shell:
        "macs2 callpeak --nomodel --extsize 200 --broad -t {input.chip} -c {input.input} -n {params.prefix} && mv {params.outfile} {output[0]}"




rule run_epic_merge:
    input:
        matrixes = expand("{{prefix}}/data/epic/{cell}.matrix.gz",
                          cell=cells),
        bed = expand("{{prefix}}/data/{{caller}}/{cell}.bed",
                     cell=cells)
    output:
        "{prefix}/data/epic-merge/{caller}/matrixes.gz"
    threads:
        24
    shell:
        "epic-merge -cpu {threads} -r {input.bed} -o {output[0]} -m {input.matrixes}"



rule test_epic_merge:
    input:
        matrixes = expand("{{prefix}}/data/epic/{cell}.matrix.gz",
                            cell=cells),
    output:
        "{prefix}/data/epic-merge/test/matrixes.gz"
    threads:
        24
    shell:
        "epic-merge -cpu {threads} -o {output[0]} -m {input.matrixes}"
